export const menuGroup = {
  id: 111,
  groupHeading: "cities",
  options: [
    {
      id: 201,
      label: "Hyderabad-label",
      value: "Hyderabad-value",
      groupHeading: "Hyderabad tourist places",
      options: [
        { id: 301, label: "charminar", value: "charminar" },
        { id: 302, label: "Hussain Sagar Lake", value: "Hussain Sagar Lake" },
        { id: 303, label: "NTR Gardens", value: "NTR Gardens" },
        { id: 304, label: "Ramoji Film City", value: "Ramoji Film City" },
        { id: 305, label: "Golconda Fort", value: "Golconda Fort" },
        { id: 306, label: "Salar Jung Museum", value: "Salar Jung Museum" },
        { id: 307, label: "Chowmahalla Palace", value: "Chowmahalla Palace" },
        { id: 308, label: "Durgam Cheruvu", value: "Durgam Cheruvu" },
      ],
    },
    {
      id: 202,
      label: "Vizag",
      value: "Vizag",
      groupHeading: "Vizag tourist places",
      options: [
        { id: 401, label: "charminar", value: "charminar" },
        {
          id: 402,
          label: "Hussain Sagar Lake",
          value: "Hussain Sagar Lake",
        },
        { id: 403, label: "NTR Gardens", value: "NTR Gardens" },
        { id: 404, label: "Ramoji Film City", value: "Ramoji Film City" },
        {
          id: 405,
          label: "Golconda Fort",
          value: "Golconda Fort",
          groupHeading: "Hyd tourist places",
          options: [
            { id: 501, label: "charminar", value: "charminar" },
            {
              id: 502,
              label: "Hussain Sagar Lake",
              value: "Hussain Sagar Lake",
            },
            { id: 503, label: "NTR Gardens", value: "NTR Gardens" },
            { id: 504, label: "Ramoji Film City", value: "Ramoji Film City" },
            { id: 505, label: "Golconda Fort", value: "Golconda Fort" },
            { id: 506, label: "Salar Jung Museum", value: "Salar Jung Museum" },
            {
              id: 507,
              label: "Chowmahalla Palace",
              value: "Chowmahalla Palace",
            },
            { id: 508, label: "Durgam Cheruvu", value: "Durgam Cheruvu" },
          ],
        },
        { id: 406, label: "Salar Jung Museum", value: "Salar Jung Museum" },
        {
          id: 407,
          label: "Chowmahalla Palace",
          value: "Chowmahalla Palace",
        },
        { id: 408, label: "Durgam Cheruvu", value: "Durgam Cheruvu" },
      ],
    },
    { id: 203, label: "Chennai", value: "Chennai" },
    { id: 204, label: "Benagaluru", value: "Benagaluru" },
    { id: 205, label: "Mumbai", value: "Mumbai" },
    { id: 206, label: "Delhi", value: "Delhi" },
    { id: 207, label: "Pune-label", value: "Pune-value" },
  ],
};
